aeschli.vscode-css-formatter
anseki.vscode-color
Asuka.insertnumbers
bradlc.vscode-tailwindcss
burkeholland.simple-react-snippets
christian-kohler.path-intellisense
dbaeumer.vscode-eslint
docsmsft.docs-yaml
donjayamanne.githistory
dsznajder.es7-react-js-snippets
eamodio.gitlens
ecmel.vscode-html-css
esbenp.prettier-vscode
formulahendry.auto-rename-tag
formulahendry.code-runner
GitHub.vscode-pull-request-github
golang.go
golang.go-nightly
KevinRose.vsc-python-indent
marp-team.marp-vscode
mgmcdermott.vscode-language-babel
mhutchie.git-graph
mohd-akram.vscode-html-format
mosapride.zenkaku
ms-azuretools.vscode-docker
MS-CEINTL.vscode-language-pack-ja
ms-kubernetes-tools.vscode-kubernetes-tools
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-vscode.cmake-tools
ms-vscode.cpptools
ms-vscode.cpptools-extension-pack
ms-vscode.cpptools-themes
ms-vscode.live-server
ms-vscode.vscode-typescript-next
msyrus.go-doc
oderwat.indent-rainbow
PKief.material-icon-theme
pnp.polacode
pranaygp.vscode-css-peek
Prisma.prisma
redhat.vscode-yaml
ritwickdey.LiveServer
sdras.night-owl
shd101wyy.markdown-preview-enhanced
streetsidesoftware.code-spell-checker
stylelint.vscode-stylelint
TabNine.tabnine-vscode
tht13.python
twxs.cmake
vincaslt.highlight-matching-tag
VisualStudioExptTeam.intellicode-api-usage-examples
VisualStudioExptTeam.vscodeintellicode
vmsynkov.colonize
wix.vscode-import-cost
xabikos.JavaScriptSnippets
yzhang.markdown-all-in-one
zhang-renyang.chat-gpt
Zignd.html-css-class-completion